set:
  resample: false
  features_train: false
  features_eval: false
  make_tfrecord: false
  train: false
  eval: false
  n_runs: 50

path:
  root_dir:  /project/jens/DCASE2021-Task5/Development_Set
  train_dir: ${path.root_dir}/Training_Set
  eval_dir:  ${path.root_dir}/Validation_Set
  feat_path: ${path.root_dir}/FeaturesN500_${features.type}
  feat_train: ${path.feat_path}/feat_train
  feat_eval:  ${path.feat_path}/feat_eval
  model: ${path.root_dir}/ModelAlldata
  best_model: ${path.model}/best_model
  last_model: ${path.model}/last_model
  results: ${path.root_dir}/ResultsAlldata

features:
  type: pcen_lowpass
  seg_len: 0.200
  hop_seg: 0.050
  fmax: 11025
  sr: 22050
  n_fft: 1024
  n_mels: 128
  hop_mel: 256
  time_constant: 0.2
  gain: 0.98
  bias: 2.
  power: 0.5
  eps: 1e-6
  center: true
  use_negative: 500
train:
  n_shot: 5
  n_query: 55
  k_way : 0
  lr: 0.0001
  scheduler_gamma: 0.5
  patience: 3
  epochs: 100
  test_split: 0.25
  binary: false
  cycle_binary: false
  label_smoothing: 0.
model:
  dims: 2
  preprocess: mel
  pool: none
  distance_fn: euclid

eval:
  samples_neg: 650
  iterations: 10
  query_batch_size: 256
  negative_set_batch_size : 256
