set:
  resample: false
  features_train: false
  features_eval: false
  train: false
  eval: false

path:
  root_dir:  /project/jens/DCASE2021-Task5/Development_Set
  train_dir: ${path.root_dir}/Training_Set
  eval_dir:  ${path.root_dir}/Validation_Set
  feat_path: ${path.root_dir}/Features_${features.type}
  feat_train: ${path.feat_path}/feat_train
  feat_eval:  ${path.feat_path}/feat_eval
  Model: ${path.root_dir}/Model
  best_model: ${path.Model}/best_model.h5
  last_model: ${path.Model}/last_model.h5
  results: ${path.root_dir}/Results

features:
  type: pcen
  seg_len: 0.200
  hop_seg: 0.050
  fmax: 11025
  sr: 22050
  n_fft: 1024
  n_mels: 128
  hop_mel: 256
  time_constant: 0.2
train:
  n_shot: 5
  n_query: 55
  k_way : 10
  lr: 0.0001
  scheduler_gamma: 0.5
  patience: 3
  epochs: 100
  test_split: 0.25
model:
  dims: 2
  preprocess: mel

eval:
  samples_neg: 650
  iterations: 25
  query_batch_size: 256
  negative_set_batch_size : 256
